from setuptools import setup

setup(name='CoFEA',
      version='0.1',
      description="mesh converter which is a part of the CoFEA Initiative project",
      long_description="",
      python_requires=">=3.7",
      author='Slawomir Polanski',
      author_email='polanski.slawomir@gmail.com',
      license='TODO',
      packages=['meshpresso', 'docs'],
      zip_safe=False,
      install_requires=[
          'jinja2',
          'sphinx-book-theme',
          'ipygany',
          'jupyter-sphinx',
          'sphinx-copybutton',
          'sphinx-togglebutton',
          "sphinxcontrib-bibtex",
          "sphinx-thebe",
          "ablog",
          "myst-parser",
          "pyvista",
          "ipykernel==5.5.0",
          'ipywidgets<8,>=7.0.0',],
      )
